- name: install yum packages
  yum: name={{ yum_packages  }}  state=latest enablerepo={{ extra_repo }}

- name: add cloud-user to group
  user: name=cloud-user append=yes groups=stapdev

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: restart machine
  shell: /sbin/shutdown -r +1  "Ansible updates triggered"
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=80 timeout=10 connect_timeout=5
  sudo: false

- name: verify stap works
  command: stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
