---
- hosts: rhel
  sudo: yes

  vars_prompt:
    - name: "redhat_login"
      prompt: "what is your redhat login?"
      default: null
    - name: "redhat_login_password"
      prompt: "what is your redhat password?"
      default: null

  roles:
    - rhel
    - common
    - otp-systap

- hosts: centos
  sudo: yes
  environment:
    KERL_CONFIGURE_OPTIONS: "--with-dynamic-trace=systemtap --with-ssl --disable-hipe"
  roles:
    - centos
    - common
    - otp-systap
