---
- hosts: rhel
  sudo: yes

  vars_prompt:
    - name: "redhat_login"
      prompt: "what is your redhat login?"
      default: null
    - name: "redhat_login_password"
      prompt: "what is your redhat password?"
      default: null

  roles:
    - rhel
    - common


- hosts: centos
  sudo: yes
  roles:
    - centos
    - common
